export const designTokens = {
  primary: '#0A5DC2',
  primaryDark: '#0847A0',
  primarySoft: '#EAF2FC',
  background: '#F7F8FA',
  surface: '#FFFFFF',
  surfaceMuted: '#F8FAFC',
  surfaceStrong: '#EDF1F6',
  text: '#18212E',
  textMuted: '#5D6B7E',
  textFaint: '#8895A7',
  border: '#E1E6ED',
  borderStrong: '#CBD4DF',
  success: '#087A4E',
  successSoft: '#ECFDF5',
  warning: '#A95A08',
  warningSoft: '#FFF8E8',
  danger: '#BC3038',
  dangerSoft: '#FFF1F2',
  radius: 8,
} as const
