<script setup lang="ts">
import { ref } from 'vue'
import { message } from 'ant-design-vue'
import { previewImport, commitImport } from '/@/api/admin-import'
import type { ImportPreview } from '/@/types/api'
const type = ref<'organizations'|'users'>('organizations'); const preview = ref<ImportPreview>(); const loading = ref(false)
async function choose(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; loading.value = true; try { preview.value = await previewImport(type.value, file) } finally { loading.value = false } }
async function commit() { if (!preview.value || preview.value.errors.length) return; await commitImport(preview.value.jobId); message.success('导入已提交'); preview.value = undefined }
</script>
<template><section class="admin-page"><div class="page-heading"><div><h1>批量导入</h1><p>支持 CSV / Excel；先预览校验，错误为零后一次性提交。</p></div><a-radio-group v-model:value="type" button-style="solid"><a-radio-button value="organizations">组织</a-radio-button><a-radio-button value="users">员工</a-radio-button></a-radio-group></div><div class="import-panel"><a-alert type="info" show-icon message="模板字段" :description="type === 'organizations' ? '组织编码、组织名称、组织类型编码、父组织编码、负责人英文名、排序' : '中文名、英文名、邮箱、手机号、主组织编码、岗位编码、角色编码、直属上级英文名'" /><label class="upload"><input type="file" accept=".csv,.xlsx" :disabled="loading" @change="choose" /><span>{{ loading ? '正在解析…' : '选择 CSV / Excel 文件' }}</span></label></div><template v-if="preview"><div class="preview-head"><strong>预览 {{ preview.rowCount }} 行</strong><a-tag :color="preview.errors.length ? 'red' : 'green'">{{ preview.errors.length ? `${preview.errors.length} 个错误` : '校验通过' }}</a-tag><a-button class="pms-primary-button" :disabled="!!preview.errors.length" @click="commit">确认导入</a-button></div><a-table :data-source="preview.errors" row-key="row" size="small"><a-table-column title="行" data-index="row" /><a-table-column title="字段" data-index="field" /><a-table-column title="错误" data-index="message" /></a-table></template></section></template>
<style scoped>.admin-page{display:grid;gap:16px}.page-heading,.preview-head{display:flex;align-items:center;justify-content:space-between;gap:16px}h1{margin:0;font-size:var(--pms-font-size-display)}p{margin:6px 0 0;color:var(--pms-text-muted);font-size:var(--pms-font-size-compact)}.import-panel{display:grid;gap:16px;padding:20px;background:var(--pms-surface);border:1px solid var(--pms-border);border-radius:var(--pms-radius)}.upload{display:grid;place-items:center;min-height:140px;color:var(--pms-primary);border:1px dashed var(--pms-border-strong);border-radius:var(--pms-radius);cursor:pointer}.upload input{display:none}</style>
