<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { message, Modal } from 'ant-design-vue'
import { listRoles, saveRole, deleteRole } from '/@/api/admin-role'
import { getOrgTree } from '/@/api/admin-org'
import type { OrgUnit, Role } from '/@/types/domain'
const roles = ref<Role[]>([]); const open = ref(false); const editing = ref<number>(); const loading = ref(false)
const form = reactive({ code: '', name: '', dataScopeType: 'SELF', enabled: true, permissionCodes: [] as string[], customOrgUnitIds: [] as number[] })
type OrgOption = OrgUnit & { level: number }
const orgOptions = ref<OrgOption[]>([])
function flattenOrg(units: OrgUnit[], level = 0): OrgOption[] { return units.flatMap(unit => [{ ...unit, level }, ...flattenOrg(unit.children || [], level + 1)]) }
const permissionOptions = ['admin:user:read', 'admin:user:write', 'admin:org:read', 'admin:org:write', 'admin:role:read', 'admin:role:write', 'admin:import:write', 'admin:audit:read', 'project:read', 'project:write']
async function load() { loading.value = true; try { roles.value = await listRoles() } finally { loading.value = false } }
function edit(role?: Role) { editing.value = role?.id; Object.assign(form, role ? { code: role.code, name: role.name, dataScopeType: role.dataScopeType, enabled: role.enabled, permissionCodes: [...role.permissionCodes], customOrgUnitIds: [...(role.customOrgUnitIds || [])] } : { code: '', name: '', dataScopeType: 'SELF', enabled: true, permissionCodes: [], customOrgUnitIds: [] }); open.value = true }
async function save() { await saveRole(form, editing.value); open.value = false; message.success('角色已保存'); await load() }
function remove(role: Role) { Modal.confirm({ title: `删除角色 ${role.name}？`, okType: 'danger', onOk: async () => { await deleteRole(role.id); message.success('角色已删除'); await load() } }) }
onMounted(async () => { await Promise.all([load(), getOrgTree().then(tree => { orgOptions.value = flattenOrg(tree) }).catch(() => undefined)]) })
</script>
<template><section class="admin-page"><div class="page-heading"><div><h1>角色管理</h1><p>按权限点与数据范围配置角色，内置角色由系统保护。</p></div><a-button class="pms-primary-button" @click="edit()">+ 新增角色</a-button></div><a-table :data-source="roles" :loading="loading" row-key="id"><a-table-column title="角色" key="name"><template #default="{ record }"><strong>{{ record.name }}</strong><div class="muted">{{ record.code }}</div></template></a-table-column><a-table-column title="数据范围" data-index="dataScopeType" /><a-table-column title="权限点" key="permissions"><template #default="{ record }">{{ record.permissionCodes?.length || 0 }} 项</template></a-table-column><a-table-column title="属性" key="builtin"><template #default="{ record }"><a-tag v-if="record.builtin" color="blue">内置</a-tag><a-tag v-if="!record.enabled">已停用</a-tag></template></a-table-column><a-table-column title="操作" key="action"><template #default="{ record }"><a-button type="link" @click="edit(record)">编辑</a-button><a-button v-if="!record.builtin" type="link" danger @click="remove(record)">删除</a-button></template></a-table-column></a-table><a-modal v-model:open="open" :title="editing ? '编辑角色' : '新增角色'" ok-text="保存" @ok="save"><a-form layout="vertical"><a-form-item label="角色编码" required><a-input v-model:value="form.code" :disabled="!!editing" placeholder="例如：PROJECT_REVIEWER" /></a-form-item><a-form-item label="角色名称" required><a-input v-model:value="form.name" /></a-form-item><a-form-item label="数据范围"><a-select v-model:value="form.dataScopeType" style="width:100%"><a-select-option value="SELF">仅本人</a-select-option><a-select-option value="SELF_AND_SUBORDINATES">本人及下属</a-select-option><a-select-option value="ORG">本组织</a-select-option><a-select-option value="ORG_AND_DESCENDANTS">本组织及下级</a-select-option><a-select-option value="CUSTOM_ORGS">自定义组织</a-select-option><a-select-option value="ALL">全公司</a-select-option></a-select><a-select v-if="form.dataScopeType === 'CUSTOM_ORGS'" v-model:value="form.customOrgUnitIds" mode="multiple" show-search option-filter-prop="label" placeholder="选择允许访问的组织" style="width:100%;margin-top:8px"><a-select-option v-for="org in orgOptions" :key="org.id" :value="org.id" :label="org.name">{{ '　'.repeat(org.level) }}{{ org.name }}</a-select-option></a-select></a-form-item><a-form-item label="权限点"><a-checkbox-group v-model:value="form.permissionCodes" :options="permissionOptions" /></a-form-item></a-form></a-modal></section></template>
<style scoped>.admin-page{display:grid;gap:16px}.page-heading{display:flex;justify-content:space-between;gap:16px}h1{margin:0;font-size:var(--pms-font-size-display)}p,.muted{margin:6px 0 0;color:var(--pms-text-muted);font-size:var(--pms-font-size-compact)}:deep(.ant-table-thead>tr>th){background:var(--pms-surface-strong);color:var(--pms-text-muted);font-size:var(--pms-font-size-caption)}</style>
